#!/bin/sh

set -e

#
# BASIC SCRIPT VARIABLES
#

OWN_DIR="$( realpath -s "$(dirname "${0}")" )"
WORKSPACE_ROOT="${WORKSPACE_ROOT:-"${OWN_DIR}"}"
WORKSPACE_SCRIPTS_DIR="${WORKSPACE_SCRIPTS_DIR:-"${WORKSPACE_ROOT}/scripts"}"
WORKSPACE_SCRIPTS_INCLUDE_DIR="${WORKSPACE_SCRIPTS_INCLUDE_DIR:-"${WORKSPACE_SCRIPTS_DIR}/include"}"

. "${WORKSPACE_SCRIPTS_INCLUDE_DIR}/template.inc.sh"

#
# DEPENDENT ENV FILES
#

_source_tpl_env_file host.env

#
# TARGET FILE GENERATION
#

_do_generate_file() {
    local _target_file
    _target_file="${1}"; shift
cat >"${_target_file}" <<EOF
# AUTOGENERATED AT $(date -Ins -u)

# This file is included by the Compose file initialized by
# the Devcontainer extension. All env-vars present here will be
# available in the guest (devcontainer), and only there.
#

WORKSPACE_ROOT="/workspace"
WEST_WORKSPACE_DIRNAME="${WEST_WORKSPACE_DIRNAME}"
ZEPHYR_BASE="${GUEST_ZEPHYR_BASE:-"/workspace/${WEST_WORKSPACE_DIRNAME}/${ZEPHYR_DIRNAME}"}"

WORKSPACE_NAME="${WORKSPACE_NAME}"
ZEPHYR_DIRNAME="${ZEPHYR_DIRNAME}"

TZ="${TZ}"
LANG="${LANG}"
LC_CTYPE="${LC_CTYPE}"
LC_TIME="${LC_TIME}"

DOCKER_HOST_IP="${DOCKER_HOST_IP}"

HOST_PROXY_HOST="${HOST_PROXY_HOST}"
HOST_PROXY_PORT="${HOST_PROXY_PORT}"

HOST_GDB_HOST="${HOST_GDB_HOST}"
HOST_GDB_PORT="${HOST_GDB_PORT}"
EOF
}

_generate_target_file

log_verbose_ok 'Done.'
